Brak pomysłu na coś ambitniejszego
vagrant326/Dziedziczenie pull request #11
Opened 2021-01-23 08:09 UTC by Atelir

2021-01-28 20:32 UTC, vagrant326 requested changes

2021-01-28 20:32 UTC, vagrant326 commented on BS055954/Program.cs
> +        }
Interfejs powinien pochodzić z mojego projektu. Proszę zaciągnąć referencję do projektu Dziedziczenie

2021-01-28 20:32 UTC, vagrant326 commented on BS055954/Program.cs
> +        public class KlasaTestowa : Silnik, IPojazd
Klasa implementująca Silnik powinna być oddzielna od implementacji IPojazdu

2021-01-28 20:32 UTC, vagrant326 commented on Dziedziczenie.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Dziedziczenie", "Dziedziczenie\Dziedziczenie.csproj", "{247DF9EA-7B57-4188-AD27-92E36FF605F6}"
Dlaczego zmieniło się ID mojego projektu? Prosiłbym żeby przywrócić stare ID. To zepsuje projekty innych studentów.

2021-01-29 16:39 UTC, Atelir commented
Wyskakuje mi taki komunikat jak próbuję poprawić to ID
![2021-01-29 17_38_54-Window](https://user-images.githubusercontent.com/71586470/106302141-de3b3b80-6258-11eb-96cf-defdfad911fc.png)

2021-01-30 12:39 UTC, vagrant326 requested changes

2021-01-30 12:39 UTC, vagrant326 commented on Dziedziczenie.sln
> -EndProject
Zgubił Pan endproject. Podejrzewam że to może być ważne.

2021-01-30 13:26 UTC, Atelir commented
Powinno być teraz ok. Dodałem Endproject po projekcie

2021-01-30 15:45 UTC, merged