v1(Zadanie8)
vagrant326/Dziedziczenie pull request #2
Opened 2021-01-19 18:21 UTC by sp055

2021-01-28 19:44 UTC, vagrant326 requested changes

2021-01-28 19:44 UTC, vagrant326 commented on SP055938/Program.cs
> +                Console.Clear();
Usunie Pan wpisy innych osób a chciałbym żeby wszystkie były widoczne. Może Pan wstawić jakiś separator, ale proszę nie czyścić konsoli

2021-01-28 19:44 UTC, vagrant326 commented on SP055938/Program.cs
> +            string next;
GitHub pokazuje mi choinkę że zmienna nie jest używana.

2021-01-28 19:44 UTC, vagrant326 commented on SP055938/Program.cs
> +        }
Funkcja Main będzie w moim projekcie, w którym zbiorę Wasze prace. Jeśli ma Pan ciekawy/zabawny pomysł na IPojazd, proszę go umieścić w funkcji Jedz.

2021-01-29 00:02 UTC, sp055 commented
*poprawka 1* usunąłem funkcję main
              *poprawka 2* usunałem niepotrzebną zmienną
              *poprawka 3* Console.SetCursorPosition przeskoczy i nadpisze tylko te linie w konsoli 
             które wyświetla moja implementacja a nie tak jak przy Console.Clear

2021-01-30 12:36 UTC, vagrant326 requested changes

2021-01-30 12:36 UTC, vagrant326 commented on SP055938/Program.cs
> +                Console.SetCursorPosition(Console.CursorLeft, Console.CursorTop - 5);
Ta część w obu funkcjach jest taka sama. Może warto by ją wyciągnąć do wspólnej metody?

2021-01-30 21:56 UTC, sp055 commented
*poprawka 4* przeniosłem "ruch" samochodziku do jednej funkcji

2021-01-31 16:51 UTC, vagrant326 requested changes

2021-01-31 16:51 UTC, vagrant326 commented on Dziedziczenie.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Dziedziczenie", "Dziedziczenie\Dziedziczenie.csproj", "{247DF9EA-7B57-4188-AD27-92E36FF605F6}"
Prosiłbym jeszcze żeby przywrócił Pan moje ID projektu/solucji. To może zepsuć pracę innym studentom.

2021-01-31 17:15 UTC, sp055 commented
Poprawiłem ID

2021-02-12 16:04 UTC, vagrant326 approved these changes

2021-02-12 16:05 UTC, merged