t
vagrant326/Dziedziczenie pull request #4
Opened 2021-01-19 19:11 UTC by mikeyMike6

2021-01-28 19:54 UTC, vagrant326 requested changes

2021-01-28 19:54 UTC, vagrant326 commented on Dziedziczenie.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Dziedziczenie", "Dziedziczenie\Dziedziczenie.csproj", "{247DF9EA-7B57-4188-AD27-92E36FF605F6}"
Dlaczego zmieniło się ID mojego projektu? Prosiłbym żeby przywrócić stare ID. To zepsuje projekty innych studentów.

2021-01-28 19:54 UTC, vagrant326 commented on MS055950/Automobil.cs
> +        public static void ClearCurrentConsoleLine()
Obawiam się że usunie Pan wpisy innych osób a chciałbym żeby wszystkie były widoczne. Może Pan wstawić jakiś separator, ale proszę nie czyścić konsoli

2021-01-28 19:54 UTC, vagrant326 commented on MS055950/Automobil.cs
> +                        Console.SetCursorPosition(p, Console.CursorTop - 1);
J/W

2021-01-28 19:54 UTC, vagrant326 commented on ProjektWykonywalny/Program.cs
> +        }
Funkcja Main będzie w moim projekcie, w którym zbiorę Wasze prace.

2021-02-12 14:17 UTC, mikeyMike6 commented on Dziedziczenie.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Dziedziczenie", "Dziedziczenie\Dziedziczenie.csproj", "{247DF9EA-7B57-4188-AD27-92E36FF605F6}"
Nie do końca rozumiem, sam nie modyfikowałem pliku w żaden sposób i więc nie rozumiem w jaki sposób mógłbym ID zmienić

2021-02-12 14:30 UTC, mikeyMike6 commented on MS055950/Automobil.cs
> +        public static void ClearCurrentConsoleLine()
ClearCurrentConsoleLine usuwa jedynie 3 ostatnie linijki, wiec znikać powinny tylko te wywołane przez mój kod

2021-02-12 16:23 UTC, vagrant326 commented on Dziedziczenie.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Dziedziczenie", "Dziedziczenie\Dziedziczenie.csproj", "{247DF9EA-7B57-4188-AD27-92E36FF605F6}"
Visual Studio mógł zrobić to automatycznie ale uprzejmie proszę żeby ręcznie Pan to zmienił. To spowoduje wiele problemów w pracach pozostałych studentów

2021-02-12 16:24 UTC, vagrant326 commented on MS055950/MS055950.csproj
> +    <OutputType>Exe</OutputType>
Proszę jeszcze zmienić typ projektu na Bibliotekę DLL (Library)

2021-02-16 17:48 UTC, mikeyMike6 commented on Dziedziczenie.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Dziedziczenie", "Dziedziczenie\Dziedziczenie.csproj", "{247DF9EA-7B57-4188-AD27-92E36FF605F6}"
Podmieniłem na ID z Pańskiego projektu więc powinno być ok

2021-02-16 17:53 UTC, mikeyMike6 commented on MS055950/MS055950.csproj
> +    <OutputType>Exe</OutputType>
Poprawione

2021-02-17 21:08 UTC, vagrant326 requested changes

2021-02-17 21:08 UTC, vagrant326 commented on MS055950/Automobil.cs
> +    }
Coś nie zagrało w klamrach? Jest błąd kompilacji

2021-02-18 15:38 UTC, mikeyMike6 commented on MS055950/Automobil.cs
> +    }
musiała się wkraść jedna klamra, usunąłem

2021-02-19 21:47 UTC, merged